##CRIAÇÃO TABELA USUARIO
CREATE TABLE usuario(
	matricula INT(8) NOT NULL AUTO_INCREMENT,
	senha VARCHAR(50) NOT NULL,
	nome VARCHAR(25) NOT NULL,
	email VARCHAR(50) NOT NULL,
	tipo_usuario INT(3) NOT NULL,
	CONSTRAINT pk_usuario PRIMARY KEY(matricula)
);

##CRIAÇÃO DA TABELA TIPO USUARIO
CREATE TABLE tipo_usuario(
	id INT(3) NOT NULL AUTO_INCREMENT,
	descricao_curta VARCHAR(30) NOT NULL,
	descricao_longa VARCHAR(200),
	CONSTRAINT pk_tipo_usuario PRIMARY KEY(id)
);

##INSERÇÃO DO TIPO USUARIO MASTER
INSERT INTO tipo_usuario(descricao_curta, descricao_longa)
VALUES('MASTER', 'Usuario master do sistema com todas as permissões');

##VINCULO DAS TABELAS USUARIO E TIPO_USUARIO
ALTER TABLE usuario
ADD CONSTRAINT fk_tipo_usuario FOREIGN KEY(tipo_usuario) REFERENCES tipo_usuario(id);

##CRIAÇÃO DA TABELA ESTABELECIMENTO
CREATE TABLE estabelecimento(
	codEstab INT(4) NOT NULL AUTO_INCREMENT,
	nome VARCHAR(30) NOT NULL,
	rua VARCHAR(100) NOT null,
	bairro VARCHAR(100) NOT NULL,
	cidade VARCHAR(100) NOT NULL,
	estado VARCHAR(100) NOT NULL,
	pais VARCHAR(100) NOT NULL,
	CONSTRAINT pk_estabelecimento PRIMARY KEY(codEstab)
);

##CRIAÇÃO DA TABELA FUNCIONARIO
CREATE TABLE funcionario(
	cod INT(8) NOT NULL AUTO_INCREMENT,
	nome VARCHAR(25) NOT NULL,
	nomeCompleto VARCHAR(100) NOT NULL,
	cpf VARCHAR(14) NOT NULL,
	funcao INT(4) NOT NULL,
	encarregado INT(8),
	estabelecimento INT(4) NOT NULL,
	CONSTRAINT pk_funcionario PRIMARY KEY(cod)
);

##CRIAÇÃO DE UMA TABELA PARA O ENDERECO DO FUNCIONARIO
CREATE TABLE funcionario_endereco(
	codEndereco INT(4) NOT NULL AUTO_INCREMENT,
	codFuncionario INT(8) NOT NULL,
	rua VARCHAR(100) NOT null,
	bairro VARCHAR(100) NOT NULL,
	cidade VARCHAR(100) NOT NULL,
	estado VARCHAR(100) NOT NULL,
	pais VARCHAR(100) NOT NULL,
	CONSTRAINT pk_funcionario_endereco PRIMARY KEY(codEndereco),
	CONSTRAINT fk_funcionario FOREIGN KEY(codFuncionario) REFERENCES funcionario(cod)
);

##CRIAÇÃO DA TABELA PARA OS TELEFONES DO FUNCIONARIO
CREATE TABLE funcionario_telefone(
	codTelefone INT(4) NOT NULL AUTO_INCREMENT,
	codFuncionario INT(8) NOT NULL,
	ddd INT(3) NOT NULL,
	telefone VARCHAR(9) NOT NULL,
	CONSTRAINT pk_funcionario_telefone PRIMARY KEY(codTelefone)
);

##CRIAÇÃO DA TABELA PARA FUNÇÕES QUE O FUNCIONARIO DESESPENHA DENTRO DA EMPRESA
CREATE TABLE funcao(
	codFuncao INT(4) NOT NULL AUTO_INCREMENT,
	funcao VARCHAR(20) NOT NULL,
	CONSTRAINT pk_funcao PRIMARY KEY(codFuncao)
);

##ALTEREÇÃO PARA INCLUIR UMA LIGAÇÃO ENTRE A TABELA FUNCIONARIO E FUNCAO
ALTER TABLE funcionario
ADD CONSTRAINT fk_funcao FOREIGN KEY(funcao) REFERENCES funcao(codFuncao);

##ALTERAÇÃO PARA INCLUIR UMA LIGAÇÃO ENTRE A TABELA FUNCIONARIO E TELEFONE
ALTER TABLE funcionario_telefone
ADD CONSTRAINT fk_funcionario_ FOREIGN KEY(codFuncionario) REFERENCES funcionario(cod);

##CRIAÇÃO DA TABELA ESTOQUE GRUPO
##NESTA TABELA OS ITENS IGUAIS ESTARAM AGRUPADOS TENDO ASSIM ACESSO A QUANTIDADE DE FORMA MAIS FÁCIL
CREATE TABLE estoque_grupo(
	codEstoque INT(11) NOT NULL AUTO_INCREMENT,
	categoria INT(8) NOT NULL, ##referece a categoria do grupo, por exemplo: água, vinho, arroz...
	setor INT(8) NOT NULL, ##referece ao setor que é posto no mercado, como liquidos, congelado...
	descricao VARCHAR(25),
	CONSTRAINT pk_estoque_grupo PRIMARY KEY(codEstoque)
);
##INSERÇÃO DE CAMPOS ESQUECIDOS
ALTER TABLE estoque_grupo
ADD COLUMN quantidade INT(4) NOT NULL;

##CRIAÇÃO DA TABELA CATEGORIA
##NESTA TEBELA ESTARAM OS TIPOS DE CATEGORIAS POSSIVEIS, COMO POR EXEMPLO:
##AGUA, VINHO, SUCO, CARNE VERMELHA, FRANGO, PEIXE, RAÇÃO CANINCA...
CREATE TABLE categoria(
	codCategoria INT(8) NOT NULL,
	nome VARCHAR(30) NOT NULL,
	CONSTRAINT pk_categoria PRIMARY KEY(codCategoria)
);

##CRIAÇÃO DA TABELA SETOR
##NESTA TABELA ESTARAM OS SETORES QUE FICAM CADA CATEGORIA
##EXEMPLO: LIMPEZA, BEBIDAS, CARNES...
CREATE TABLE setor(
	codSetor INT(8) NOT NULL,
	nome VARCHAR(30) NOT NULL,
	CONSTRAINT pk_setor PRIMARY KEY(codSetor)
);

##ALTERÇÃO DA TEBELA ESTOQUE PARA CRIAR VINCULOS COM AS TEBLAS CATEGORIA E SETOR
ALTER TABLE estoque_grupo
ADD CONSTRAINT fk_setor FOREIGN KEY(setor) REFERENCES setor(codSetor),
ADD CONSTRAINT fk_categoria FOREIGN key(categoria) REFERENCES categoria(codCategoria);


###############################################################################################################
############################################OQUE TEM PRA FAZER
##CRIAR TABELA ESTOQUE ITEM
##CRIAR TABELA PARA O HISTORICO DE COMPRAS
##CRIAR TABELA PARA O HISTORICO DE SAIDAS
##CRIAR TABELA AUXILIAR PRA TIPOS DE SAIDAS: VENDA, PERDA POR VENCIMENTO, PERDA POR OUTROS MOTIVOS