package view;

import control.Funcao;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import model.TableModel;


public class Funcoes extends javax.swing.JInternalFrame {

    private final Main main;
    private final TableModel tModel;
    
    public Funcoes(Main main){
        this.main = main;
        
        initComponents();
        
        //****Constroi tabela
        String[] colunas = {"", "id", "Função"};
        this.tModel = new TableModel(colunas);
        //****Carrega tabela
        this.loadTable();
        //****Seta modelo
        tableFuncionarios.setModel(this.tModel);
    }

    public void loadTable(){
        //Carregamento da tabela
        Funcao funcao = new Funcao();
        Map<String, String> filtros = new HashMap<>();
        //Preencher os filtros
        try{
            ArrayList<Map> listaEstab = funcao.lista(filtros);
            listaEstab.forEach((Map e) -> {
                Funcoes.this.tModel.addRow(new Object[]{
                    Boolean.FALSE,
                    e.get("id"),
                    e.get("funcao")
                });
            });
        }catch(SQLException ex){
            System.out.println("Erro ao listar tabelas: "+ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFuncionarios = new javax.swing.JTable();
        bAddFuncionario = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        bPesquisar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bEditFunc = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setBorder(null);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableFuncionarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 690, 340));

        bAddFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_24px.png"))); // NOI18N
        bAddFuncionario.setText("Novo");
        bAddFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(bAddFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 150, 65));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 610, -1));

        bPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/procurar_24px.png"))); // NOI18N
        bPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPesquisarMouseClicked(evt);
            }
        });
        getContentPane().add(bPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 35, -1, -1));

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, -1, -1));

        bEditFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_24px.png"))); // NOI18N
        bEditFunc.setText("Editar");
        bEditFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditFuncActionPerformed(evt);
            }
        });
        getContentPane().add(bEditFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 150, 65));

        bExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close_16px.png"))); // NOI18N
        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(bExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 150, 65));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/turnback_24px.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        setBounds(0, 0, 730, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void bAddFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddFuncionarioActionPerformed
        //CadFuncionario cadFunc = new CadFuncionario(this);
        //cadFunc.setVisible(true);
    }//GEN-LAST:event_bAddFuncionarioActionPerformed

    private void bPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPesquisarMouseClicked
        System.out.println("Vai relizar a pesquisa");
    }//GEN-LAST:event_bPesquisarMouseClicked

    private void bEditFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditFuncActionPerformed
        /*CadFuncionario cadFunc;
        ArrayList<Integer> selected = this.tModel.getIdSelected();
        switch(selected.size()){
            case 0:
            JOptionPane.showMessageDialog(rootPane,"Selecione um item para edição","",JOptionPane.INFORMATION_MESSAGE);
            break;
            case 1:
            try{
                cadFunc = new CadFuncionario(this, selected.get(0));
                cadFunc.setVisible(true);
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(rootPane,"Ocorreu um erro, por favor contate o superte tecnico.\n"+ex,"Erro",JOptionPane.ERROR_MESSAGE);
            }
            break;
            default:
            JOptionPane.showMessageDialog(rootPane,"Só é possível editar até 1 itens","",JOptionPane.INFORMATION_MESSAGE);
            break;
        }
        this.tModel.setAllUnselect();*/
    }//GEN-LAST:event_bEditFuncActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        /*Funcionario func = new Funcionario();
        Integer rs;
        ArrayList<Integer> selected = this.tModel.getIdSelected();

        rs = func.excluir(selected);
        switch(rs){
            case 1:
            this.tModel.removeRow();
            JOptionPane.showMessageDialog(rootPane,"Funcionario excluido com sucesso","Sucesso",JOptionPane.INFORMATION_MESSAGE);
            break;
            case 1451:
            JOptionPane.showMessageDialog(rootPane,"Não foi possível excluir esse funcionario, existem informações dependeste dele no sistema","Error",JOptionPane.ERROR_MESSAGE);
            break;
            default:
            JOptionPane.showMessageDialog(rootPane,"Algo de arrado aconteceu. \nCódigo de erro: "+rs,"Error",JOptionPane.ERROR_MESSAGE);
            break;
        }
        this.tModel.setAllUnselect();*/
    }//GEN-LAST:event_bExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddFuncionario;
    private javax.swing.JButton bEditFunc;
    private javax.swing.JButton bExcluir;
    private javax.swing.JLabel bPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableFuncionarios;
    // End of variables declaration//GEN-END:variables
}
