package view;

import control.Funcao;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

import model.TableModel;


public class Funcoes extends javax.swing.JInternalFrame {

    private final Main main;
    private final TableModel tModel;
    
    public Funcoes(Main main){
        this.main = main;
        
        initComponents();
        
        //****Constroi tabela
        String[] colunas = {"", "id", "Função"};
        this.tModel = new TableModel(colunas);
        //****Carrega tabela
        this.loadTable();
        //****Seta modelo
        tableFuncionarios.setModel(this.tModel);
    }

    public void loadTable(){
        //Carregamento da tabela
        Funcao funcao = new Funcao();
        Map<String, String> filtros = new HashMap<>();
        //Preencher os filtros
        try{
            ArrayList<Map> listaFuncoes = funcao.lista(filtros);
            listaFuncoes.forEach((Map e) -> {
                Funcoes.this.tModel.addRow(new Object[]{
                    Boolean.FALSE,
                    e.get("id"),
                    e.get("funcao")
                });
            });
        }catch(SQLException ex){
            System.out.println("Erro ao listar tabelas: "+ex);
        }
    }
    
    public void addFuncao(Funcao f){
        //Atualizar tabela quando for feito o cadastro de um novo funcionario
        this.tModel.addRow(new Object[]{Boolean.FALSE,f.getIdFuncao(),f.getDescricao()});
    }
    
    public void updateFuncaoInTheTable(Funcao f){
        //Atualizar tabela quando for atualizado um funcionario ta lista
        Integer index = this.tModel.getIndexById(f.getIdFuncao());
        this.tModel.updateRow(index, new Object[]{
            Boolean.FALSE,
            Integer.toString(f.getIdFuncao()),//Na hora de pegar a matricula tem que tornar ela um String
            f.getDescricao()
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFuncionarios = new javax.swing.JTable();
        bAddFuncao = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        bPesquisar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bEditar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();
        bVoltar = new javax.swing.JButton();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setBorder(null);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableFuncionarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 690, 340));

        bAddFuncao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_24px.png"))); // NOI18N
        bAddFuncao.setText("Novo");
        bAddFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddFuncaoActionPerformed(evt);
            }
        });
        getContentPane().add(bAddFuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 150, 65));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 610, -1));

        bPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/procurar_24px.png"))); // NOI18N
        bPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPesquisarMouseClicked(evt);
            }
        });
        getContentPane().add(bPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 35, -1, -1));

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, -1, -1));

        bEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_24px.png"))); // NOI18N
        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });
        getContentPane().add(bEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 150, 65));

        bExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close_16px.png"))); // NOI18N
        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(bExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 150, 65));

        bVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/turnback_24px.png"))); // NOI18N
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(bVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        setBounds(0, 0, 730, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void bAddFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddFuncaoActionPerformed
        CadFuncao cadFuncao = new CadFuncao(this);
        cadFuncao.setVisible(true);
    }//GEN-LAST:event_bAddFuncaoActionPerformed

    private void bPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPesquisarMouseClicked
        System.out.println("Vai relizar a pesquisa");
    }//GEN-LAST:event_bPesquisarMouseClicked

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        CadFuncao cadFuncao;
        ArrayList<Integer> selected = this.tModel.getIdSelected();
        switch(selected.size()){
            case 0:
            JOptionPane.showMessageDialog(rootPane,"Selecione um item para edição","",JOptionPane.INFORMATION_MESSAGE);
            break;
            case 1:
            try{
                cadFuncao = new CadFuncao(this, selected.get(0));
                cadFuncao.setVisible(true);
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(rootPane,"Ocorreu um erro, por favor contate o superte tecnico.\n"+ex,"Erro",JOptionPane.ERROR_MESSAGE);
            }
            break;
            default:
            JOptionPane.showMessageDialog(rootPane,"Só é possível editar até 1 itens","",JOptionPane.INFORMATION_MESSAGE);
            break;
        }
        this.tModel.setAllUnselect();
    }//GEN-LAST:event_bEditarActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        Funcao funcao = new Funcao();
        Integer rs;
        ArrayList<Integer> selected = this.tModel.getIdSelected();

        rs = funcao.excluir(selected);
        switch(rs){
            case 1:
            this.tModel.removeRow();
            JOptionPane.showMessageDialog(rootPane,"Excluido com sucesso",
                                        "Sucesso",JOptionPane.INFORMATION_MESSAGE);
            break;
            case 1451:
            JOptionPane.showMessageDialog(rootPane,"Há funcionarios dessa função, por isso não foi possível exclui-la",
                                            "Error",JOptionPane.ERROR_MESSAGE);
            break;
            default:
            JOptionPane.showMessageDialog(rootPane,"Algo de arrado aconteceu. \nCódigo de erro: "+rs,
                                        "Error",JOptionPane.ERROR_MESSAGE);
            break;
        }
        this.tModel.setAllUnselect();
    }//GEN-LAST:event_bExcluirActionPerformed

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        this.main.fechaTelas();
        this.main.getFuncionarios().setVisible(true);
    }//GEN-LAST:event_bVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddFuncao;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JLabel bPesquisar;
    private javax.swing.JButton bVoltar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableFuncionarios;
    // End of variables declaration//GEN-END:variables
}
